name: cloud_sync_shared_preferences_adapter
description: A Flutter plugin for integrating Shared Preferences sync functionality.
version: 0.0.1
repository: https://github.com/lamnhan066/cloud_sync_adapters

environment:
  sdk: ^3.7.0

resolution: workspace

dependencies:
  cloud_sync: ^0.2.1
  shared_preferences: ^2.5.3

dev_dependencies:
  lints: ^5.0.0
  test: ^1.24.0
