name: cloud_sync_shared_preferences_adapter
description: A Flutter plugin for integrating Shared Preferences sync functionality.
version: 0.0.1-rc.3
repository: https://github.com/lamnhan066/cloud_sync_adapters

environment:
  sdk: ^3.7.0

resolution: workspace

dependencies:
  flutter:
    sdk: flutter
  cloud_sync: ^0.4.0-rc.3
  shared_preferences: ^2.5.3

dev_dependencies:
  lints: ^5.0.0
  mocktail: ^1.0.4
  flutter_test:
    sdk: flutter
