name: cloud_sync_google_drive_adapter
description: A Flutter plugin for integrating Google Drive cloud sync functionality.
version: 0.0.1-rc.1
repository: https://github.com/lamnhan066/cloud_sync_adapters

environment:
  sdk: ^3.7.0

resolution: workspace

dependencies:
  cloud_sync: ^0.4.0-rc.1
  googleapis: ^14.0.0

dev_dependencies:
  lints: ^5.0.0
  mocktail: ^1.0.4
  test: ^1.24.0
